import 'dart:async';
import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:share_plus/share_plus.dart';
import 'package:shared_preferences/shared_preferences.dart';
void main()=>runApp(const NoPenApp());
const green=Color(0xFF31D6A0),ink=Color(0xFF0C1B24);
const speech=MethodChannel('nopen/speech'),events=EventChannel('nopen/speech_events');
class Report{final String title,date,transcript,summary;final List<String> topics,decisions,actions;const Report(this.title,this.date,this.transcript,this.summary,this.topics,this.decisions,this.actions);Map<String,dynamic> json()=>{'title':title,'date':date,'transcript':transcript,'summary':summary,'topics':topics,'decisions':decisions,'actions':actions};factory Report.from(Map<String,dynamic>j)=>Report(j['title']??'',j['date']??'',j['transcript']??'',j['summary']??'',List<String>.from(j['topics']??[]),List<String>.from(j['decisions']??[]),List<String>.from(j['actions']??[]));String text()=>'$title\n$date\n\nÖZET\n$summary\n\nKONULAR\n${topics.join('\n')}\n\nKARARLAR\n${decisions.join('\n')}\n\nAKSİYONLAR\n${actions.join('\n')}\n\nTRANSKRİPT\n$transcript';}
class NoPenApp extends StatelessWidget{const NoPenApp({super.key});@override Widget build(BuildContext c)=>MaterialApp(debugShowCheckedModeBanner:false,theme:ThemeData(useMaterial3:true,colorScheme:ColorScheme.fromSeed(seedColor:green)),home:const Shell());}
class Shell extends StatefulWidget{const Shell({super.key});@override State<Shell>createState()=>_Shell();}
class _Shell extends State<Shell>{int i=0;@override Widget build(BuildContext c)=>Scaffold(body:IndexedStack(index:i,children:const[Home(),Archive(),Settings()]),bottomNavigationBar:NavigationBar(selectedIndex:i,onDestinationSelected:(v)=>setState(()=>i=v),destinations:const[NavigationDestination(icon:Icon(Icons.home),label:'Ana Sayfa'),NavigationDestination(icon:Icon(Icons.inventory_2),label:'Arşiv'),NavigationDestination(icon:Icon(Icons.settings),label:'Ayarlar')]));}
class Home extends StatelessWidget{const Home({super.key});Future<void>add(BuildContext c)async{final x=TextEditingController();final t=await showDialog<String>(context:c,builder:(d)=>AlertDialog(title:const Text('Yeni Toplantı'),content:TextField(controller:x,autofocus:true,decoration:const InputDecoration(labelText:'Toplantı adı')),actions:[TextButton(onPressed:()=>Navigator.pop(d),child:const Text('İptal')),FilledButton(onPressed:(){if(x.text.trim().isNotEmpty)Navigator.pop(d,x.text.trim());},child:const Text('Başlat'))]));x.dispose();if(t!=null&&c.mounted)Navigator.push(c,MaterialPageRoute(builder:(_)=>Live(t)));}@override Widget build(BuildContext c)=>SafeArea(child:ListView(padding:const EdgeInsets.all(24),children:[const Text('NoPen',style:TextStyle(fontSize:30,fontWeight:FontWeight.bold)),const SizedBox(height:30),Card(child:Padding(padding:const EdgeInsets.all(24),child:Column(children:[const Icon(Icons.mic,size:55,color:green),const SizedBox(height:16),const Text('Yeni Toplantı',style:TextStyle(fontSize:23,fontWeight:FontWeight.bold)),const Text('Ses kaydı oluşturmadan canlı Türkçe transkript.'),const SizedBox(height:20),FilledButton.icon(onPressed:()=>add(c),icon:const Icon(Icons.add),label:const Text('Toplantı Oluştur'))]))]));}
class Live extends StatefulWidget{final String title;const Live(this.title,{super.key});@override State<Live>createState()=>_Live();}
class _Live extends State<Live>{StreamSubscription?sub;Timer?timer;int sec=0;String finalText='',partial='';bool active=false;@override void initState(){super.initState();start();}Future<void>start()async{try{if(!(await speech.invokeMethod<bool>('isAvailable')??false))throw Exception('Cihaz içi STT desteklenmiyor.');sub=events.receiveBroadcastStream().listen((e){final m=Map<String,dynamic>.from(e as Map);if(m['final']==true){finalText+='${finalText.isEmpty?'':'\n'}${m['text']}';partial='';}else partial='${m['text']}';if(mounted)setState((){});});await speech.invokeMethod('start',{'locale':'tr-TR'});timer=Timer.periodic(const Duration(seconds:1),(_){if(mounted)setState(()=>sec++);});if(mounted)setState(()=>active=true);}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('$e')));}}Future<void>end()async{timer?.cancel();await speech.invokeMethod('stop');await sub?.cancel();final full=[finalText,partial].where((e)=>e.trim().isNotEmpty).join('\n');final r=makeReport(widget.title,full);final p=await SharedPreferences.getInstance();final l=p.getStringList('reports')??[];l.insert(0,jsonEncode(r.json()));await p.setStringList('reports',l);if(mounted)Navigator.pushReplacement(context,MaterialPageRoute(builder:(_)=>ReportPage(r)));}@override void dispose(){timer?.cancel();sub?.cancel();speech.invokeMethod('stop');super.dispose();}@override Widget build(BuildContext c)=>Scaffold(backgroundColor:ink,body:SafeArea(child:Padding(padding:const EdgeInsets.all(22),child:Column(children:[Text(widget.title,style:const TextStyle(color:Colors.white70)),const SizedBox(height:15),const Text('Toplantı Dinleniyor',style:TextStyle(color:Colors.white,fontSize:27,fontWeight:FontWeight.bold)),const Spacer(),const Icon(Icons.mic,color:green,size:100),Text('${(sec~/60).toString().padLeft(2,'0')}:${(sec%60).toString().padLeft(2,'0')}',style:const TextStyle(color:Colors.white,fontSize:28)),Text(active?'● Canlı dinleme':'Başlatılıyor',style:const TextStyle(color:green)),const Spacer(),Container(height:180,width:double.infinity,padding:const EdgeInsets.all(15),decoration:BoxDecoration(color:Colors.white10,borderRadius:BorderRadius.circular(18)),child:SingleChildScrollView(reverse:true,child:Text([finalText,partial].where((e)=>e.isNotEmpty).join('\n'),style:const TextStyle(color:Colors.white)))),const SizedBox(height:15),SizedBox(width:double.infinity,child:FilledButton.icon(onPressed:end,icon:const Icon(Icons.stop),label:const Text('Toplantıyı Bitir')))]))));}}
Report makeReport(String title,String text){final l=text.split(RegExp(r'[\n.!?]+')).map((e)=>e.trim()).where((e)=>e.length>8).toList();return Report(title,DateTime.now().toString().substring(0,16),text,l.take(3).join('. '),l.take(5).toList(),l.where((e)=>RegExp(r'karar|olacak|kabul',caseSensitive:false).hasMatch(e)).take(6).toList(),l.where((e)=>RegExp(r'yapacak|hazırlayacak|gönderecek|aksiyon|sorumlu',caseSensitive:false).hasMatch(e)).take(6).toList());}
class ReportPage extends StatelessWidget{final Report r;const ReportPage(this.r,{super.key});Widget s(String t,List<String>x)=>Card(child:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(t,style:const TextStyle(fontSize:18,fontWeight:FontWeight.bold)),...x.map((e)=>Text('• $e'))])));@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Toplantı Raporu')),body:ListView(padding:const EdgeInsets.all(18),children:[Text(r.title,style:const TextStyle(fontSize:24,fontWeight:FontWeight.bold)),s('Özet',[r.summary]),s('Konu Başlıkları',r.topics),s('Kararlar',r.decisions),s('Aksiyonlar',r.actions),FilledButton.icon(onPressed:()=>Share.share(r.text(),subject:r.title),icon:const Icon(Icons.share),label:const Text('Paylaş'))]));}
class Archive extends StatefulWidget{const Archive({super.key});@override State<Archive>createState()=>_Archive();}class _Archive extends State<Archive>{List<Report>r=[];@override void initState(){super.initState();load();}Future<void>load()async{final p=await SharedPreferences.getInstance();r=(p.getStringList('reports')??[]).map((e)=>Report.from(jsonDecode(e))).toList();if(mounted)setState((){});}@override Widget build(BuildContext c)=>SafeArea(child:ListView(padding:const EdgeInsets.all(20),children:[const Text('Arşiv',style:TextStyle(fontSize:28,fontWeight:FontWeight.bold)),...r.map((e)=>Card(child:ListTile(title:Text(e.title),subtitle:Text(e.date),onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>ReportPage(e))))))]));}
class Settings extends StatelessWidget{const Settings({super.key});@override Widget build(BuildContext c)=>const SafeArea(child:Padding(padding:EdgeInsets.all(20),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Ayarlar',style:TextStyle(fontSize:28,fontWeight:FontWeight.bold)),ListTile(leading:Icon(Icons.mic),title:Text('Cihaz içi Türkçe STT')),ListTile(leading:Icon(Icons.privacy_tip),title:Text('Ses kaydı oluşturulmaz')),ListTile(leading:Icon(Icons.info),title:Text('NoPen v0.1.0'))])));}
